sudo: false
os:
  - linux
 # - osx
addons:
  apt:
    packages:
      - libasound2-dev
haxe:
  - "3.3.0"
  - development
neko: "2.0.0"
matrix:
  allow_failures:
    - haxe: development 
compiler:
  - gcc
#  - clang
before_script:
  - git clone https://github.com/ktxsoftware/nodejs_bin.git
  - git clone --recursive https://github.com/ktxsoftware/kha.git
  - nodejs_bin/copysysbin.sh
  - haxelib install utest
script: 
  - nodejs_bin/node kha/make.js --from tests/ . --to tests/build -t html5
  - nodejs_bin/node tests/build/html5/kha.js