sudo: false
language: nodejs
os:
  - linux
 # - osx
addons:
  apt:
    packages:
      - libasound2-dev
language: cpp
compiler:
  - gcc
#  - clang
before_script:
#  - git clone https://github.com/ktxsoftware/nodejs_bin.git
  - git clone --recursive https://github.com/ktxsoftware/kha.git
  - find .
#  - nodejs_bin/copysysbin.sh
script: 
  - node kha/make.js --from tests/ . --to tests/kha-build -t html5
  - node build/html5/kha.js