sudo: false
language: haxe
haxe:
  - "3.2.0"
  - development
neko: "2.0.0"
matrix:
  allow_failures:
    - haxe: development # Allow development to fail until I have time to investigate.
os:
  - linux
 # - osx
addons:
  apt:
    packages:
      - libasound2-dev
install:
  - haxelib install utest
before_script:
  - git clone https://github.com/ktxsoftware/nodejs_bin.git
  - git clone --recursive https://github.com/ktxsoftware/kha.git
  - nodejs_bin/copysysbin.sh

script: 
  - nodejs_bin/node kha/make.js --from tests/ . --to tests/build -t html5 -h ~/haxe
  - tests/build/project-html5.hxml
  - nodejs_bin/node tests/build/html5/kha.js