sudo: false
os:
  - linux
 # - osx
addons:
  apt:
    packages:
      - libasound2-dev
language: cpp
compiler:
  - gcc
#  - clang
before_script:
  - git clone https://github.com/ktxsoftware/nodejs_bin.git
  - git clone --recursive https://github.com/ktxsoftware/kha.git
  - find .
  - nodejs_bin/copysysbin.sh
script: 
  - cd tests/
  - ../nodejs_bin/node ../kha/make.js html5
  - ../nodejs_bin/node build/html5/kha.js